---
fixtures:
  forge_modules:
    archive: "puppet/archive"
    augeas_core: "puppetlabs/augeas_core"
    inifile: "puppetlabs/inifile"
    java: "puppetlabs/java"
    stdlib: "puppetlabs/stdlib"
    systemd: "puppet/systemd"
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
