spec/spec_helper.rb:
  mock_with: ':rspec'
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.tag_pattern = "%s"
        t.tag_message_pattern = "Release version %s\nSee CHANGELOG.md for details"
        t.commit_message_pattern = "Bump version to %s"
        t.tag_sign = true
      end
